### ISSUE TITLE
Failing at "Linking .pioenvs/pd-stepper-blinds-2/firmware.elf"

### ISSUE THREAD

**Issue by wshankles** [slimcdk/esphome-custom-components#7]
I'm using joshr120's pd stepper. Trying to add a motor load sensor and it fails. 

Linking .pioenvs/pd-stepper-blinds-2/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pioenvs/pd-stepper-blinds-2/src/main.o:(.literal._Z5setupv+0x2bc): undefined reference to `vtable for esphome::tmc2209_sensor::MotorLoadSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld: .pioenvs/pd-stepper-blinds-2/src/main.o:(.literal._Z5setupv+0x2c0): undefined reference to `vtable for esphome::tmc2209_sensor::MotorLoadSensor'
collect2: error: ld returned 1 exit status
*** [.pioenvs/pd-stepper-blinds-2/firmware.elf] Error 1
========================= [FAILED] Took 40.94 seconds =========================

**Comment by slimcdk** [comment]
Try to clean the build files and compile again. I'll see if there is anything I can do to fix this.

**Comment by wshankles** [comment]
> Try cleaning the build files and compile again. I'll see if there is anything I can do to fix this.

That was it. Thank you.

**Comment by slimcdk** [comment]
This seems to be a general issue with ESP-IDF (in ESPhome) and requires watching for config and file changes on another level than component level. I've added a [section](https://github.com/slimcdk/esphome-custom-components/tree/a16f8d25fe152e24d89d9b685dee5744beee74e9/esphome/components/tmc2209#undefined-reference-to-vtable) under troubleshooting for this particular issue.
